<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <RootNamespace>FishSyncClient.Gui</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="icon.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.13" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
        <!-- Diagnostics tooling for the Debug build only -->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.13" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="NeoSmart.PrettySize" Version="3.1.1" />
        <PackageReference Include="FishBucket" Version="0.0.2" />
        <PackageReference Include="FishBucket.SyncClient" Version="0.0.1" />
        <PackageReference Include="FishBucket.ApiClient" Version="0.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\FishSyncClient.csproj" />
    </ItemGroup>

</Project>
